name: dockerizing app 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - env:
          NAME: ${{secrets.DOCKER_USERNAME}}/house-pricing
          TAG: $$(git log -1 --pretty=%!H(MISSING))
          IMG: ${NAME}:${TAG}
          LATEST: ${NAME}:latest
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${IMG} .
      - name: docker login
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: docker tag
        run: docker tag ${IMG} ${LATEST}
      - name: docker push
        run: docker push ${NAME}
 
