name: dockerizing app 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: log
        run: git rev-parse --short HEAD
      - name: docker build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/house-pricing .
      - name: docker login
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/house-pricing:latest

  deploy-to-heroku:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "thawing-beyond-04979"
          heroku_email: "abedn352@gmail.com"
          usedocker: 1
          dontuseforce: 1
      - run: heroku stack:set heroku-20
