name: dockerizing app

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - name: docker build
        uses: actions/checkout@v1
        with:
          args: build -t abedalrahman/house-pricing .
      - name: docker login
        uses: actions/checkout@v1
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push abedalrahman/house-pricing
 
