name: dockerizing app 2

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker build
        run: docker build -t ${{secrets.DOCKER_USERNAME}}/house-pricing:$$(git log -1 --pretty=%!H(MISSING)) .
      - name: docker login
        uses: docker/login-action@v1
        with:
          password: ${{ secrets.DOCKER_PASSWORD }}
          username: ${{ secrets.DOCKER_USERNAME }}
      - name: docker tag
        run: docker tag ${{secrets.DOCKER_USERNAME}}/house-pricing:$$(git log -1 --pretty=%!H(MISSING)) ${{secrets.DOCKER_USERNAME}}/house-pricing:$$(git log -1 --pretty=%!H(MISSING)):latest
      - name: docker push
        run: docker push ${{secrets.DOCKER_USERNAME}}/house-pricing
 
